name: Build Fabric
on:
  pull_request:
    types:
      - reopened
      - synchronize
      - opened
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/setup-gradle@v3
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - run: echo "TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
      - run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - run: gradle :fabric:build --no-daemon